package com.openlattice.shuttle.util;

import com.openlattice.shuttle.dates.TimeZones;
import java.util.TimeZone;

public final class Constants {
    public static final String ADDRESS_OBJECT      = "addressObject";
    public static final String COLUMN              = "column";
    public static final String COLUMNS             = "columns";
    public static final String CONDITIONS          = "conditions";
    public static final String DATE_COLUMN         = "dateColumn";
    public static final String DATE_PATTERN        = "datePattern";
    public static final String ELSE                = "valueElse";
    public static final String GOAL                = "goal";
    public static final String HASH_FUNCTION       = "hashFunction";
    public static final String IF_MORE_THAN        = "ifMoreThan";
    public static final String IGNORE_CASE         = "ignoreCase";
    public static final String INDEX               = "index";
    public static final String LAT_TRANSFORMS      = "latTransforms";
    public static final String LOC                 = "location";
    public static final String LON_TRANSFORMS      = "lonTransforms";
    public static final String NOTNULL             = "notNull";
    public static final String PARTIAL             = "partial";
    public static final String PATTERN             = "pattern";
    public static final String PATTERNS            = "patterns";
    public static final String PREFIX              = "prefix";
    public static final String READER              = "reader";
    public static final String REVERSE             = "reverse";
    public static final String SEP                 = "separator";
    public static final String STORAGE_DESTINATION = "storageDest";
    public static final String STRING              = "string";
    public static final String SUFFIX              = "suffix";
    public static final String TARGET              = "target";
    public static final String TIME_COLUMN         = "timeColumn";
    public static final String TIME_PATTERN        = "timePattern";
    public static final String GENERATOR           = "generator";
    public static final String TRANSFORMS          = "transforms";
    public static final String TRANSFORM_VALUE_MAPPER = "transformValueMapper";
    public static final String TRANSFORMS_IF_FALSE = "transformsIfFalse";
    public static final String TRANSFORMS_IF_TRUE  = "transformsIfTrue";
    public static final String TYPE                = "type";
    public static final String UPDATE_TYPE         = "updateType";
    public static final String VALUE               = "value";
    public static final String LEFTCOLUMN          = "leftColumn";
    public static final String LEFTTRANSFORMS      = "leftTransforms";
    public static final String RIGHTCOLUMN         = "rightColumn";
    public static final String RIGHTTRANSFORMS     = "rightTransforms";
    public static final String COMPARISON          = "comparison";
    public static final String TIMEZONE            = "timezone";
    public static final String OPERATOR            = "operator";
    public static final TimeZone DEFAULT_TIMEZONE  = TimeZones.America_NewYork;
    public static final String LENGTH              = "length";
    public static final String PRE                 = "pre";
    public static final String CUTOFF              = "cutoff";
}
