# FROM openlattice/ol-base:latest
# FROM openjdk:16-jre-slim
FROM openjdk:11-jre-slim

RUN useradd -m openlattice && \
    mkdir -p /opt/openlattice/logging/ && \
    chown -R openlattice:openlattice /opt/openlattice

VOLUME /opt/openlattice/logging/

EXPOSE 5701
EXPOSE 5702
EXPOSE 5703

VOLUME /etc/secrets/

WORKDIR /opt/openlattice/

COPY ./conductor/build/distributions/conductor.tgz /opt/openlattice/

RUN tar xzvf conductor.tgz

# ARG JAVA_OPTS
# ENV JAVA_OPTS="-xmx"

ARG SERVICE_ARGS
ENV SERVICE_ARGS="kubernetes postgres medialocal auditlocal"

CMD ["/opt/openlattice/conductor/bin/conductor", "kubernetes", "postgres", "edmsync", "medialocal" , "auditlocal"]