# FROM openlattice/ol-base:latest
# FROM openjdk:16-jre-slim
FROM openjdk:11-jre-slim

RUN useradd -m openlattice && \
    mkdir -p /opt/openlattice/logging/ && \
    chown -R openlattice:openlattice /opt/openlattice

VOLUME /opt/openlattice/logging/

EXPOSE 8080
EXPOSE 8443

WORKDIR /opt/openlattice/

COPY ./datastore/build/distributions/datastore.tgz /opt/openlattice/

RUN tar xzvf datastore.tgz

# ARG JAVA_OPTS
# ENV JAVA_OPTS="-xmx"

ARG SERVICE_ARGS
ENV SERVICE_ARGS="kubernetes postgres medialocal auditlocal"

CMD ["/opt/openlattice/datastore/bin/datastore", "kubernetes", "postgres", "medialocal" , "auditlocal"]