

/*
 * Copyright (C) 2018. OpenLattice, Inc.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * You can contact the owner of the copyright at support@openlattice.com
 *
 */

package com.openlattice.hazelcast;

public enum HazelcastMap {
    ACL_KEYS,
    APPS,
    APP_TYPES,
    APP_CONFIGS,
    ASSEMBLIES,
    ASSOCIATION_TYPES,
    AUDIT_LOG,
    AUDIT_METRICS,
    AUDIT_RECORD_ENTITY_SETS,
    BACKEDGES,
    COMPLEX_TYPES,
    DATA,
    DB_CREDS,
    DELETION_LOCKS,
    EDGES,
    ENTITY_DATA,
    ENTITY_LINKING_LOCKS,
    ENTITY_SET_COLLECTION_CONFIG,
    ENTITY_SET_COLLECTIONS,
    ENTITY_SET_COUNTERS,
    ENTITY_SET_PROPERTIES_TICKETS,
    ENTITY_SET_PROPERTY_METADATA,
    ENTITY_SET_TICKETS,
    ENTITY_SETS,
    ENTITY_TYPE_COLLECTIONS,
    ENTITY_TYPE_PROPERTY_METADATA,
    ENTITY_TYPES,
    EXPIRATION_LOCKS,
    HBA_AUTHENTICATION_RECORDS,
    IDS,
    ID_GENERATION,
    ID_REF_COUNTS,
    ID_CACHE,
    INDEXING_JOBS,
    INDEXING_LOCKS,
    INDEXING_PROGRESS,
    INDEXING_PARTITION_PROGRESS,
    INDEXING_PARTITION_LIST,
    INDEXING_GRAPH_PROCESSING,
    INTEGRATIONS,
    KEYS,
    LINKED_ENTITY_TYPES,
    LINKED_ENTITY_SETS,
    LINKING_CURSORS,
    LINKING_EDGES,
    LINKING_ENTITIES,
    LINKING_ENTITY_VERTICES,
    LINKING_FEEDBACK,
    LINKING_INDEXING_LOCKS,
    LINKING_LOCKS,
    LINKING_VERTICES,
    LONG_IDS,
    MATERIALIZED_ENTITY_SETS,
    PERMISSIONS,
    PERMISSIONS_REQUESTS_UNRESOLVED,
    PERMISSIONS_REQUESTS_RESOLVED,
    PRINCIPAL_TREES,
    PROPERTY_TYPES,
    ORGANIZATION_APPS,
    ORGANIZATIONS,
    NAMES,
    SCHEMAS,
    @Deprecated VISIBILITY,
    ORGANIZATIONS_TITLES,
    ORGANIZATIONS_DESCRIPTIONS,
    ALLOWED_EMAIL_DOMAINS,
    ORGANIZATIONS_MEMBERS,
    SMS_INFORMATION,
    PRINCIPALS,
    ORGANIZATIONS_ROLES,
    REQUESTS,
    SECURABLE_OBJECT_TYPES,
    TOKEN_ACCEPTANCE_TIME,
    USERS,
    VERTICES,
    VERTEX_IDS_AFTER_LINKING,
    PERSISTENT_SEARCHES,
    ENTITY_WRITE_LOCKS,
    ORGANIZATION_EXTERNAL_DATABASE_COLUMN,
    ORGANIZATION_EXTERNAL_DATABASE_TABLE,
    TRIGGERS,
    SECURABLE_PRINCIPALS,
    RESOLVED_PRINCIPAL_TREES
}


